# Generated by Django 2.2.1 on 2019-05-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='modify_on',
            field=models.DateField(auto_now=True, null=True, verbose_name='Modificado em'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='update_on',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Atualizado em'),
        ),
    ]
