# Generated by Django 2.2.1 on 2019-05-02 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterField(
            model_name='livro',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
